name: Your Workflow Name

on:
  push:
    branches:
      - main

jobs:
  your-job-name:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add more steps as needed
